### ISSUE TITLE
모니터링툴 설치하기

### ISSUE THREAD

**Issue by gusah009** [JavaBlooming-In-Spring/System-Design-Interview#1]
### 목적
트래픽 흐름이나 트래픽 양, 요청당 걸리는 시간을 보기 위함

- 로그 (log.info 했을 때 나오는것들, tomcat의 access-log 등등)
- 애플리케이션 메트릭 (CPU, 메모리, 디스크 네트워크 I/O)
- DB, 캐시의 메트릭

**Comment by jojaeng2** [comment]
전설의 시작..
